const { chromium } = require('playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('http://127.0.0.1:8893/');
    await page.locator('#pos').waitFor({ state: 'visible' });
    const historyBefore = (await (await page.request.get('http://127.0.0.1:8893/api/history')).json()).length;
    await page.locator('#printer-settings').click();
    await page.locator('#printer-dialog').waitFor({ state: 'visible' });
    await page.locator('#printer-backend').selectOption('agent');
    await page.locator('#printer-paper').selectOption('58');
    await page.locator('#agent-token').fill('demo-token-no-real-printer');
    await page.locator('#printer-automatic').check();
    await page.locator('#printer-form input[name="pin"]').fill('demo-local');
    await page.screenshot({ path: 'outputs/hybrid-printer-settings.png', fullPage: true });
    await page.locator('#printer-form button[type="submit"]').click();
    await page.locator('#printer-dialog').waitFor({ state: 'hidden' });
    const safeConfig = await (await page.request.get('http://127.0.0.1:8893/api/printer')).json();
    assert.equal(safeConfig.automatic,true);
    assert.equal(safeConfig.paper,'58');
    assert.ok(!('agent_token' in safeConfig));
    await page.locator('#quantity').fill('500');
    await page.locator('#search').fill('tomate');
    await page.locator('#suggestions button').click();
    await page.waitForFunction(() => document.getElementById('total').textContent.includes('1.900'));
    await page.locator('#generar-venta').click();
    await page.locator('#cash').fill('2000');
    await page.screenshot({ path: 'outputs/hybrid-desktop.png', fullPage: true });
    await page.locator('#checkout').click();
    await page.locator('#receipt-dialog').waitFor({ state: 'visible' });
    assert.match(await page.locator('#receipt-state').innerText(), /pendiente de nube/);
    assert.match(await page.locator('#receipt').innerText(), /CAMBIO: \$ 100/);
    await page.waitForFunction(() => document.getElementById('print-state').textContent.includes('Simulación:'));
    await page.locator('#print').click();
    await page.locator('#copy-dialog').waitFor({ state:'visible' });
    await page.locator('#confirm-copy').click();
    await page.waitForFunction(() => document.getElementById('print-state').textContent.includes('Simulación:'));
    assert.match(await page.locator('#receipt-state').innerText(), /pendiente de nube/);
    await page.locator('#close-receipt').click();
    await page.waitForFunction(() => document.querySelectorAll('.cart-row').length === 0);
    await page.reload();
    await page.locator('#history-panel summary').click();
    await page.locator('.history-row').first().waitFor();
    assert.equal(await page.locator('.history-row').count(), historyBefore + 1);
    await page.locator('#history button').first().click();
    await page.locator('#receipt-dialog').waitFor({ state: 'visible' });
    await page.locator('#close-receipt').click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator('#backup-settings').click();
    await page.locator('#backup-form input[name="pin"]').fill('demo-local');
    await page.locator('#backup-form input[name="password"]').fill('respaldo-demo-con-clave');
    await page.locator('#backup-form input[name="confirmation"]').fill('respaldo-demo-con-clave');
    assert.ok(await page.locator('#backup-dialog').evaluate(e=>e.scrollWidth<=e.clientWidth));
    await page.screenshot({path:'outputs/hybrid-backup-mobile.png',fullPage:true});
    const downloadReady=page.waitForEvent('download');
    await page.locator('#backup-form button[type="submit"]').click();
    const download=await downloadReady;
    assert.match(download.suggestedFilename(),/\.novabackup$/);
    await download.saveAs('outputs/hybrid-browser-demo.novabackup');
    await page.locator('#backup-dialog').waitFor({state:'hidden'});
    assert.equal(await page.locator('#backup-form input[name="password"]').inputValue(),'');
    assert.equal(await page.locator('.history-row').count(),historyBefore+1);
    await page.screenshot({ path: 'outputs/hybrid-mobile.png', fullPage: true });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.locator('#printer-settings').click();
    await page.locator('#printer-dialog').waitFor({state:'visible'});
    assert.equal(await page.locator('#agent-token').inputValue(),'');
    assert.ok(await page.locator('#printer-dialog').evaluate(e=>e.scrollWidth<=e.clientWidth));
    await page.screenshot({path:'outputs/hybrid-printer-mobile.png',fullPage:true});
    await page.locator('#cancel-printer').click();
    await page.locator('#lock').click();
    await page.locator('#unlock').waitFor({ state: 'visible' });
    await page.locator('#unlock input').fill('demo-local');
    await page.locator('#unlock button').click();
    await page.locator('#pos').waitFor({ state: 'visible' });
    assert.deepEqual(errors, []);
    console.log('OK: venta offline por gramos/stock negativo, cambio, historial, impresión simulada/copia, respaldo cifrado descargado, claves privadas, bloqueo y responsive.');
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
